# We will be investigating data types in this lesson

### The most important learnings from this lesson are 1) how to parse data in CSV files 2) how to read and manipulate Excel files in python 3) how to explore data in JSON files

## We can write function rules to write this CSV into a dictionary, however, there is a module named CSV that can be used to quicken this step.

In [1]:
import numpy as np
import pandas as pd
import os
import pprint
import csv

## Beatles Discography is our dataset

In [2]:
DATADIR = ""
DATAFILE = '/Users/marcmaybaum/Desktop/Education/Udacity/Data_Analyst_Nanodegree/Project_3/beatles-diskography.csv'

### DictReader is a class of the CSV module that is able to read all our data and place into a dictionary. It assumes the first row is a header row and that we want to use those column names for our fields in our dictionary. It deals with quote characters, blank values, and other data issues that we would have to deal with without the CSV module.

In [4]:
def parse_csv(datafile):
    data=[]
    n=0
    with open(datafile,'rb') as sd:
        r = csv.DictReader(sd)
        # line in this case is each dictionary
        for line in r:
            data.append(line)
            return data
        
if _name_ == '_main_':
    datafile = os.path.join(DATADIR, DATAFILE)
    parse_csv(datafile)
    d = parse_csv(datafile)
    pprint.pprint(d)

## Best practice when using CSVs is to use the CSV module since so many capabilities have been built out for it

## Now we look at how to programmatically read Excel files. The module is called XLRD and allows us to use .xls or .xlxs format

In [7]:
import xlrd

In [8]:
datafile = '/Users/marcmaybaum/Desktop/Education/Udacity/Data_Analyst_Nanodegree/Project_3/2013_ERCOT_Hourly_Load_Data.xls'

In [58]:
# Parse_file function will be most helpful for Excel files
def parse_file(datafile):
# Command that we use to open the notebook is .open_notebook()
    workbook = xlrd.open_workbook(datafile)
# We need to specify which sheet to use (sheet_by_index() command)    
    sheet = workbook.sheet_by_index(0)
# We are looping through rows and columns and reading it in a python list
    data = [[sheet.cell_value(r, col)
                for col in range(sheet.ncols)]
                    for r in range(sheet.nrows)]
    
# Printing out row 3, column 2 in this list    
    print ("\nList Comprehension")
    print ("data[3][2]:")
    print (data[3][2])

# Following the list comprehension, we are reading the list to row 50
# This illustrates the functions of the list and reading an excel file
    print ("\nCells in a nested loop:")
    for row in range(sheet.nrows):
        for col in range(sheet.ncols):
            if row == 50:
                print (sheet.cell_value(row,col)),
                ### other useful methods outlined to understand xlrd
                print ("\nROWS, COLUMNS, and CELLS:")
                print ("Number of rows in the sheet:"),
                print (sheet.nrows)
                print ("Tyoe of data in cell (row 3, col 2)"),
                print (sheet.cell_type(3,2))
                print ("Value in cell (row 3, col 2):"),
                print (sheet.cell_value(3,2))
                print ("Get a slice of values in column 3, from rows 1-3:")
                print (sheet.col_values(3, start_rowx=1, end_rowx=4))
                print ("\nDATES:")
                print ("Type of data in cell (row 1, col 0):")
                print (sheet.cell_type(1,0))
                exceltime = sheet.cell_value(1,0)
                print ("Time in Excel format:"),
                print (exceltime)
                print ("Convert time to a Python datetime tuple, from the Excel float:"),
                print (xlrd.xldate_as_tuple(exceltime, 0))
                # Working with date data as a tuple allows python to understand it as date data
                
print(parse_file(datafile))

List Comprehension
data[3][2]:
1036.0886969999988

Cells in a nested loop:
41277.083333333336

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
9238.737309999968

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
1438.2052799999994

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
1565.4428559999976

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
916.7083480000003

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
14010.903488000036

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
3027.9833399999993

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
6165.211119000006

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
1157.7416630000007

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
37520.93340400001

ROWS, COLUMNS, and CELLS:
Number of rows in the sheet:
7296
Tyoe of data in cell (row 3, col 2)
2
Value in cell (row 3, col 2):
1036.0886969999988
Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]

DATES:
Type of data in cell (row 1, col 0):
3
Time in Excel format:
41275.041666666664
Convert time to a Python datetime tuple, from the Excel float:
(2013, 1, 1, 1, 0, 0)
None

### Exercise to pull out data from the Excel dataset

In [11]:
# 

    data = {
        'maxtime': (0,0,0,0,0,0),
        'maxvalue': 0,
        'mintime': (0,0,0,0,0,0),
        'minvalue': 0,
        'avgcoast': 0
    }
    return data

data = parse_file(datafile)

IndentationError: unexpected indent (<ipython-input-11-05277d9e0575>, line 3)

# Intro to JSON

## There is a JSON standard for modelling and transmitting the data so there is a standard for how to organize the data

## JSON objects are just like Python dictionaries

## Python lists are similar to JSON Array

## Data Modeling in JSON
### Items may have different fields, may have nested objects, may have nested arrarys

## JSON = JavaScript Object Notation
### JSON is a syntax for storing and exchanging data
### JSON is text, written with JavaScript object notation, and can be used as a data format by any programming language


## JSON can be interpreted with Python using the json module (see below)

https://docs.python.org/2/library/json.html

## JSON arrays are interpreted as lists and JSON objects as Dictionaries

In [48]:
"""
To experiment with this code freely you will have to run this code locally.
Take a look at the main() function for an example of how to use the code. We
have provided example json output in the other code editor tabs for you to look
at, but you will not be able to run any queries through our UI.
"""
import json
import requests

BASE_URL = "http://musicbrainz.org/ws/2/"
ARTIST_URL = BASE_URL + "artist/"


# query parameters are given to the requests.get function as a dictionary; this
# variable contains some starter parameters.
query_type = {  "simple": {},
                "atr": {"inc": "aliases+tags+ratings"},
                "aliases": {"inc": "aliases"},
                "releases": {"inc": "releases"}}


def query_site(url, params, uid="", fmt="json"):
    """
    This is the main function for making queries to the musicbrainz API. The
    query should return a json document.
    """
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print ("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()


def query_by_name(url, params, name):
    """
    This adds an artist name to the query parameters before making an API call
    to the function above.
    """
    params["query"] = "artist:" + name
    return query_site(url, params)


def pretty_print(data, indent=4):
    """
    After we get our output, we can use this function to format it to be more
    readable.
    """
    if type(data) == dict:
        print (json.dumps(data, indent=indent, sort_keys=True))
    else:
        print (data)


def main():
    """
    Below is an example investigation to help you get started in your
    exploration. Modify the function calls and indexing below to answer the
    questions on the next quiz.

    HINT: Note how the output we get from the site is a multi-level JSON
    document, so try making print statements to step through the structure one
    level at a time or copy the output to a separate output file. Experimenting
    and iteration will be key to understand the structure of the data!
    """

    # Query for information in the database about bands named Nirvana
    results = query_by_name(ARTIST_URL, query_type["simple"], "One Direction")
    pretty_print(results)

    # Isolate information from the 4th band returned (index 3)
    print ("\nARTIST:")
    pretty_print(results["artists"][3])

    # Query for releases from that band using the artist_id
    artist_id = results["artists"][3]["id"]
    artist_data = query_site(ARTIST_URL, query_type["releases"], artist_id)
    releases = artist_data["releases"]

    # Print information about releases from the selected band
    print ("\nONE RELEASE:")
    pretty_print(releases[0], indent=2)

    release_titles = [r["title"] for r in releases]
    print ("\nALL TITLES:")
    for t in release_titles:
        print (t)

In [49]:
if __name__ == '__main__':
    main()

requesting http://musicbrainz.org/ws/2/artist/?query=artist%3AOne+Direction&fmt=json
{
    "artists": [
        {
            "area": {
                "id": "8a754a16-0027-3a29-b6d7-2b40ea0481ed",
                "name": "United Kingdom",
                "sort-name": "United Kingdom"
            },
            "begin-area": {
                "id": "f03d09b3-39dc-4083-afd6-159e3f0d462f",
                "name": "London",
                "sort-name": "London"
            },
            "country": "GB",
            "id": "1a425bbd-cca4-4b2c-aeb7-71cb176c828a",
            "life-span": {
                "begin": "2010-07",
                "ended": null
            },
            "name": "One Direction",
            "score": "100",
            "sort-name": "One Direction",
            "tags": [
                {
                    "count": 2,
                    "name": "pop"
                },
                {
                    "count": 1,
                    "name": "power pop"
                },
                {
                    "count": 1,
                    "name": "dance-pop"
                },
                {
                    "count": 1,
                    "name": "pop rock"
                },
                {
                    "count": 1,
                    "name": "folk pop"
                },
                {
                    "count": 2,
                    "name": "boy band"
                }
            ],
            "type": "Group"
        },
        {
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "name": "United States",
                "sort-name": "United States"
            },
            "country": "US",
            "disambiguation": "San Francisco band",
            "id": "d3479e62-76ac-4aec-9f95-5b222d1e26b1",
            "life-span": {
                "ended": null
            },
            "name": "Direction",
            "score": "69",
            "sort-name": "Direction",
            "type": "Group"
        },
        {
            "area": {
                "id": "b2bc1294-77be-4c7b-af93-9868b83b1f34",
                "name": "Auckland",
                "sort-name": "Auckland"
            },
            "disambiguation": "New Zealand punk?",
            "id": "a234ebb0-0399-4253-baf6-2ae0abc9d8f2",
            "life-span": {
                "ended": null
            },
            "name": "Direction",
            "score": "47",
            "sort-name": "Direction"
        },
        {
            "id": "47813cd0-be78-48ab-802f-1306fc180124",
            "life-span": {
                "ended": null
            },
            "name": "Loose Direction",
            "score": "43",
            "sort-name": "Loose Direction"
        },
        {
            "id": "75fb2c35-4f3a-4145-b948-da871176f039",
            "life-span": {
                "ended": null
            },
            "name": "Disco Direction",
            "score": "43",
            "sort-name": "Disco Direction"
        },
        {
            "id": "9e9d35c3-ce54-4a48-b3ba-4eebdadc1ed8",
            "life-span": {
                "ended": null
            },
            "name": "Audio Direction",
            "score": "43",
            "sort-name": "Audio Direction"
        },
        {
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "name": "United States",
                "sort-name": "United States"
            },
            "country": "US",
            "disambiguation": "USA punk band",
            "id": "d554887e-2e17-48f4-8610-624a944a9329",
            "life-span": {
                "ended": null
            },
            "name": "No Direction",
            "score": "43",
            "sort-name": "No Direction",
            "tags": [
                {
                    "count": 1,
                    "name": "punk"
                },
                {
                    "count": 1,
                    "name": "usa"
                }
            ],
            "type": "Group"
        },
        {
            "id": "6130ddae-22dd-4930-ba0f-6d59f81d3637",
            "life-span": {
                "begin": "2009-08",
                "ended": null
            },
            "name": "The Direction",
            "score": "43",
            "sort-name": "Direction, The",
            "type": "Group"
        },
        {
            "id": "355fa6a9-dba2-43b0-bd0f-a9e6dc14c79f",
            "life-span": {
                "ended": null
            },
            "name": "Direction X",
            "score": "43",
            "sort-name": "Direction X",
            "type": "Group"
        },
        {
            "id": "74c2fbfc-0ced-4f8a-9da6-7df628755757",
            "life-span": {
                "ended": null
            },
            "name": "No Direction",
            "score": "43",
            "sort-name": "No Direction",
            "type": "Group"
        },
        {
            "id": "7c4e4dc0-6a0e-4887-b374-0cc57749f563",
            "life-span": {
                "ended": null
            },
            "name": "Direction Indicator",
            "score": "43",
            "sort-name": "Direction Indicator"
        },
        {
            "id": "ce85410c-10e4-4b2e-a878-72483fcf0884",
            "life-span": {
                "ended": null
            },
            "name": "7th Direction",
            "score": "43",
            "sort-name": "7th Direction"
        },
        {
            "id": "cfd2b787-3656-44ce-9212-9e555b400af5",
            "life-span": {
                "ended": null
            },
            "name": "New Direction",
            "score": "43",
            "sort-name": "New Direction"
        },
        {
            "id": "2524b4ea-965f-4628-b940-acd0a9210047",
            "life-span": {
                "ended": null
            },
            "name": "Lost Direction",
            "score": "43",
            "sort-name": "Lost Direction"
        },
        {
            "id": "a32cc520-f2e6-4db2-8b61-c7baca599ef5",
            "life-span": {
                "ended": null
            },
            "name": "Second Direction",
            "score": "43",
            "sort-name": "Second Direction"
        },
        {
            "area": {
                "id": "ef1b7cc0-cd26-36f4-8ea0-04d9623786c7",
                "name": "Netherlands",
                "sort-name": "Netherlands"
            },
            "begin-area": {
                "id": "0b565bc6-05e7-4c3a-bc28-075fabd9a8d0",
                "name": "Maastricht",
                "sort-name": "Maastricht"
            },
            "country": "NL",
            "id": "574236dc-aa46-4194-8200-6cb039e9ddbd",
            "life-span": {
                "begin": "1989",
                "end": "2008",
                "ended": true
            },
            "name": "Right Direction",
            "score": "43",
            "sort-name": "Right Direction",
            "type": "Group"
        },
        {
            "id": "65cd1bef-0de3-439e-a2fc-a71c308c6359",
            "life-span": {
                "ended": null
            },
            "name": "\u9ad8\u67f3\u660c\u884c New Direction",
            "score": "38",
            "sort-name": "Masayuki Takayanagi New Direction"
        },
        {
            "aliases": [
                {
                    "begin-date": null,
                    "end-date": null,
                    "locale": null,
                    "name": "Masayuki \"Jojo\" Takayanagi* & New Direction For The Arts",
                    "primary": null,
                    "sort-name": "Masayuki \"Jojo\" Takayanagi* & New Direction For The Arts",
                    "type": null
                }
            ],
            "area": {
                "id": "2db42837-c832-3c27-b4a3-08198f75693c",
                "name": "Japan",
                "sort-name": "Japan"
            },
            "country": "JP",
            "id": "8367123e-9a2b-4f1a-ad22-52dee85b144a",
            "life-span": {
                "ended": null
            },
            "name": "New Direction for the Arts",
            "score": "36",
            "sort-name": "New Direction for the Arts",
            "type": "Group"
        },
        {
            "id": "3ccdd708-a6f2-4117-938d-4b23f045cbbb",
            "life-span": {
                "ended": null
            },
            "name": "The New Transit Direction",
            "score": "34",
            "sort-name": "New Transit Direction, The"
        },
        {
            "area": {
                "id": "71bbafaa-e825-3e15-8ca9-017dcad1748b",
                "name": "Canada",
                "sort-name": "Canada"
            },
            "country": "CA",
            "id": "e0027978-441c-4877-b36f-0d2833181a42",
            "life-span": {
                "ended": null
            },
            "name": "The Beat Direction",
            "score": "34",
            "sort-name": "Beat Direction, The",
            "type": "Group"
        },
        {
            "disambiguation": "rock",
            "id": "dffb4132-bfd1-4c23-8128-31c23d0b6fe9",
            "life-span": {
                "ended": null
            },
            "name": "Found My Direction",
            "score": "34",
            "sort-name": "Found My Direction"
        },
        {
            "area": {
                "id": "85752fda-13c4-31a3-bee5-0e5cb1f51dad",
                "name": "Germany",
                "sort-name": "Germany"
            },
            "country": "DE",
            "disambiguation": "Hardcore/Gabber DJ Team",
            "id": "06a2966d-95c1-4e20-a4d6-26e15d1d7e69",
            "life-span": {
                "begin": "2010",
                "ended": null
            },
            "name": "Tensor & Re-Direction",
            "score": "34",
            "sort-name": "Tensor & Re-Direction",
            "type": "Group"
        },
        {
            "area": {
                "id": "106e0bec-b638-3b37-b731-f53d507dc00e",
                "name": "Australia",
                "sort-name": "Australia"
            },
            "country": "AU",
            "disambiguation": "Hardcore band from Australia",
            "id": "6fe5e79d-c29a-4a14-91c2-f2e587cba2dd",
            "life-span": {
                "ended": null
            },
            "name": "Found My Direction",
            "score": "34",
            "sort-name": "Found My Direction",
            "type": "Group"
        },
        {
            "id": "982461f8-d0e0-44c0-9aa3-9ce9df28c71a",
            "life-span": {
                "ended": null
            },
            "name": "Moving in The Right Direction",
            "score": "31",
            "sort-name": "Moving in The Right Direction"
        },
        {
            "disambiguation": "Church choir at Lourdes",
            "id": "c2485094-3ac9-4632-b8d8-aacae7df3b6f",
            "life-span": {
                "ended": null
            },
            "name": "Chorale et assembl\u00e9e sous la direction de Jean Zune",
            "score": "30",
            "sort-name": "Chorale et assembl\u00e9e sous la direction de Jean Zune"
        }
    ],
    "count": 1764,
    "created": "2017-06-14T00:01:31.11Z",
    "offset": 0
}

ARTIST:
{
    "id": "47813cd0-be78-48ab-802f-1306fc180124",
    "life-span": {
        "ended": null
    },
    "name": "Loose Direction",
    "score": "43",
    "sort-name": "Loose Direction"
}
requesting http://musicbrainz.org/ws/2/artist/47813cd0-be78-48ab-802f-1306fc180124?inc=releases&fmt=json

ONE RELEASE:

IndexError: list index out of range

## The above code was used to look through a bunch of artists and find specific pieces of data outlined in the various objects of the JSON data.